### ISSUE TITLE
please add tag 1.7.2

### ISSUE THREAD

**Issue by mjmcmahon** [digitoimistodude/woothemes-updater#2]
Hey guys, 

Am using this with a project for a client. The site uses Trellis/bedrock and composer for plugin management. 

Could you add the 1.7.2 tag to the repo please so I can use that version?

Thanks,

Mike

**Comment by rollecode** [comment]
Hi there! We use this for the same purpose, with bedrock-fork [dudestack](https://github.com/digitoimistodude/dudestack) (still wondering why there's no official composer repository for the plugin, since it's free). 

Sorry for forgetting to update the tags, [here you go](https://github.com/digitoimistodude/woothemes-updater/releases/tag/1.7.2).

**Comment by rollecode** [comment]
Forgot that Packagist doesn't update the tag if added via GitHub and not via command line... so this was the case when the woothemes-updater got updates last time. Added note to my self and published [a new release](https://github.com/digitoimistodude/woothemes-updater/releases/tag/1.7.2). `composer update` should now work as expected. Sorry about the hassle.

**Comment by mjmcmahon** [comment]
Thanks Roni!

I agree it would be good to see it in Packagist.
